// Auto-generated type stubs for Cloudflare Workers globals.
// These types are normally generated by `wrangler types`.

declare global {
  // Cloudflare AI binding
  interface AiRunInput {
    messages?: Array<{ role: string; content: string }>;
    prompt?: string;
    [key: string]: unknown;
  }

  interface Ai {
    run(model: string, input: AiRunInput): Promise<unknown>;
  }

  // Cloudflare Workers execution context
  interface ExecutionContext {
    waitUntil(promise: Promise<unknown>): void;
    passThroughOnException(): void;
  }

  // ExportedHandler used by original scaffold (kept for compatibility)
  interface ExportedHandler<E = unknown> {
    fetch?(request: Request, env: E, ctx: ExecutionContext): Promise<Response> | Response;
    scheduled?(event: unknown, env: E, ctx: ExecutionContext): Promise<void> | void;
  }
}

export {};
